export const TotalCountries = [
    { name: "India", capital: "New Delhi" },
    { name: "USA", capital: "Washington, D.C." },
    { name: "Canada", capital: "Ottawa" },
    { name: "Australia", capital: "Canberra" },
    { name: "UK", capital: "London" },
    { name: "Germany", capital: "Berlin" },
    { name: "France", capital: "Paris" },
    { name: "Japan", capital: "Tokyo" },
    { name: "China", capital: "Beijing" },
    { name: "Russia", capital: "Moscow" },
    { name: "Brazil", capital: "Brasília" },
    { name: "South Africa", capital: "Pretoria" },
    { name: "Italy", capital: "Rome" },
    { name: "Mexico", capital: "Mexico City" },
    { name: "Spain", capital: "Madrid" },
    { name: "South Korea", capital: "Seoul" },
    { name: "Argentina", capital: "Buenos Aires" },
    { name: "Nigeria", capital: "Abuja" },
    { name: "Egypt", capital: "Cairo" },
    { name: "Turkey", capital: "Ankara" },
    { name: "Saudi Arabia", capital: "Riyadh" },
    { name: "Indonesia", capital: "Jakarta" },
    { name: "Pakistan", capital: "Islamabad" },
    { name: "Bangladesh", capital: "Dhaka" },
    { name: "Vietnam", capital: "Hanoi" },
    { name: "Philippines", capital: "Manila" },
    { name: "Thailand", capital: "Bangkok" },
    { name: "Malaysia", capital: "Kuala Lumpur" },
    { name: "Singapore", capital: "Singapore" },
    { name: "Sri Lanka", capital: "Colombo" },
    { name: "Nepal", capital: "Kathmandu" },
    { name: "Bhutan", capital: "Thimphu" },
    { name: "Myanmar", capital: "Naypyidaw" },
    { name: "Afghanistan", capital: "Kabul" },
    { name: "Iran", capital: "Tehran" },
    { name: "Iraq", capital: "Baghdad" },
    { name: "Syria", capital: "Damascus" },
    { name: "Jordan", capital: "Amman" },
    { name: "Lebanon", capital: "Beirut" },
    { name: "Israel", capital: "Jerusalem" },
    { name: "Palestine", capital: "Ramallah" },
    { name: "Qatar", capital: "Doha" },
    { name: "United Arab Emirates", capital: "Abu Dhabi" },
    { name: "Kuwait", capital: "Kuwait City" },
    { name: "Bahrain", capital: "Manama" },
    { name: "Oman", capital: "Muscat" },
    { name: "Yemen", capital: "Sana'a" },
    { name: "Morocco", capital: "Rabat" },
    { name: "Algeria", capital: "Algiers" },
    { name: "Tunisia", capital: "Tunis" },
    { name: "Libya", capital: "Tripoli" },
    { name: "Sudan", capital: "Khartoum" },
    { name: "Ethiopia", capital: "Addis Ababa" },
    { name: "Kenya", capital: "Nairobi" },
    { name: "Uganda", capital: "Kampala" },
    { name: "Tanzania", capital: "Dodoma" },
    { name: "Zimbabwe", capital: "Harare" },
    { name: "Zambia", capital: "Lusaka" },
    { name: "Mozambique", capital: "Maputo" },
    { name: "Angola", capital: "Luanda" },
    { name: "Ghana", capital: "Accra" },
    { name: "Ivory Coast", capital: "Yamoussoukro" },
    { name: "Senegal", capital: "Dakar" },
    { name: "Mali", capital: "Bamako" },
    { name: "Niger", capital: "Niamey" },
    { name: "Chad", capital: "N'Djamena" },
    { name: "Cameroon", capital: "Yaoundé" },
    { name: "Democratic Republic of the Congo", capital: "Kinshasa" },
    { name: "Somalia", capital: "Mogadishu" },
    { name: "Madagascar", capital: "Antananarivo" },
    { name: "Mauritius", capital: "Port Louis" },
    { name: "Seychelles", capital: "Victoria" },
    { name: "Maldives", capital: "Malé" },
    { name: "Iceland", capital: "Reykjavík" },
    { name: "Norway", capital: "Oslo" },
    { name: "Sweden", capital: "Stockholm" },
    { name: "Finland", capital: "Helsinki" },
    { name: "Denmark", capital: "Copenhagen" },
    { name: "Netherlands", capital: "Amsterdam" },
    { name: "Belgium", capital: "Brussels" },
    { name: "Switzerland", capital: "Bern" },
    { name: "Austria", capital: "Vienna" },
    { name: "Czech Republic", capital: "Prague" },
    { name: "Hungary", capital: "Budapest" },
    { name: "Poland", capital: "Warsaw" },
    { name: "Ukraine", capital: "Kyiv" },
    { name: "Belarus", capital: "Minsk" },
    { name: "Lithuania", capital: "Vilnius" },
    { name: "Latvia", capital: "Riga" },
    { name: "Estonia", capital: "Tallinn" },
    { name: "Portugal", capital: "Lisbon" },
    { name: "Greece", capital: "Athens" },
    { name: "Turkey", capital: "Ankara" },
    { name: "Cyprus", capital: "Nicosia" },
    { name: "Georgia", capital: "Tbilisi" },
    { name: "Armenia", capital: "Yerevan" },
    { name: "Azerbaijan", capital: "Baku" },
    { name: "Kazakhstan", capital: "Nur-Sultan" },
    { name: "Uzbekistan", capital: "Tashkent" },
    { name: "Turkmenistan", capital: "Ashgabat" },
    { name: "Kyrgyzstan", capital: "Bishkek" },
    { name: "Tajikistan", capital: "Dushanbe" }
];
